// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fTvdu1WKrC43JXmQe3I8GG8UySfrUJk',
    appId: '1:187116751094:web:20c58db5db0a7401a1c4d7',
    messagingSenderId: '187116751094',
    projectId: 'game-store-dbb39',
    authDomain: 'game-store-dbb39.firebaseapp.com',
    storageBucket: 'game-store-dbb39.firebasestorage.app',
    measurementId: 'G-Z91RBVY180',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3mD0n45C0z8bm6WALcSxi3XVe4am1JM',
    appId: '1:187116751094:android:7510f5145351c31ea1c4d7',
    messagingSenderId: '187116751094',
    projectId: 'game-store-dbb39',
    storageBucket: 'game-store-dbb39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSNCDtRR2By_tW5x7sn766fYwCDiTUNw',
    appId: '1:187116751094:ios:62feb4caee2c7803a1c4d7',
    messagingSenderId: '187116751094',
    projectId: 'game-store-dbb39',
    storageBucket: 'game-store-dbb39.firebasestorage.app',
    iosBundleId: 'com.example.gameStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSNCDtRR2By_tW5x7sn766fYwCDiTUNw',
    appId: '1:187116751094:ios:62feb4caee2c7803a1c4d7',
    messagingSenderId: '187116751094',
    projectId: 'game-store-dbb39',
    storageBucket: 'game-store-dbb39.firebasestorage.app',
    iosBundleId: 'com.example.gameStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6fTvdu1WKrC43JXmQe3I8GG8UySfrUJk',
    appId: '1:187116751094:web:55063583f12c3306a1c4d7',
    messagingSenderId: '187116751094',
    projectId: 'game-store-dbb39',
    authDomain: 'game-store-dbb39.firebaseapp.com',
    storageBucket: 'game-store-dbb39.firebasestorage.app',
    measurementId: 'G-7B6N4TVEEV',
  );
}
